site_name: Felipe Alfonso González Wiki
site_description: Personal and professional wiki of Felipe Alfonso González
site_author: Felipe Alfonso González
theme:
  name: material
nav:
  - Home: Wiki/index.md
  - Articles: Wiki/articles1.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
extra_css:
  - css/wiki-style.css
