name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: felipealfonsog
          template: classic
          base: header, activity, community, repositories

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 300

          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          commit: yes

          plugin_achievements: yes
          plugin_achievements_display: compact
