name: Deploy Wiki

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs-material

      - name: Build and Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
