name: Recent Updated Repos

on:
  push:
    paths:
      - .github/workflows/listrepos.yml
      - src/generate_listrepos.py
      - README.md

  schedule:
    - cron: '0 0 * * *'

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Generate README.md with repos
        run: python src/generate_listrepos.py

      - name: Commit changes
        run: |
          git config --global user.name 'Felipe Alfonso Gonzalez'
          git config --global user.email 'f.alfonso@res-ear.ch'
          git add README.md LISTINGREPOS.md
          git commit -m "Update README.md and listrepos.md with recent repos"
          git push -f
