name: Update-Recent-Repos

on:
  push:
    paths:
      - .github/workflows/listrepos.yml
      - src/generate-listrepos.mjs
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-repos:
    runs-on: ubuntu-latest
    env:
      NUM_REPOS: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Generate listrepos.md
        run: node --experimental-modules src/generate-listrepos.mjs $NUM_REPOS
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_LRGH }}

      - name: Configure Git user
        run: |
          git config --global user.name 'felipealfonsog'
          git config --global user.email 'actions@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add listrepos.md
          git commit -m "Update listrepos.md"
          git push
